services:
  hermes-webhook-relay:
    build:
      context: .
    volumes:
      - ./app:/app/app
    ports:
      - "8080:8080"
    image: hermes-webhook-relay:0.1
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - provider
      - egress

networks:
  provider:
    name: ${PROVIDER_DOCKER_NETWORK:-internal}
    external: true
  egress:
    driver: bridge
